spring:
  datasource:
    url: ENC(alHbibpsYseuQbQ57ytDMnn08wBTE1wEjdUby1fk8yR9SbAbY0g1+dj11m9lwr2iTqFqOka4pDorZhcskk5ESQVOCmFjb2fXobBQPDN2PsA=)
    username: ENC(zCZVSbB3E9o1K/fXjyyagweLIEOzQo4EhkZgRDqOhpnYhdkzRnxSQ6kDIzyNyLap)
    password: ENC(55quBi/fY/ZYvcg/u1JpkP+tAR17bxZM6KxGAIU6lxWC0+gvld7TWxX/JX+zW+Wz)
