spring:
  datasource:
    url: ENC(H9a8HiRQkJhFNQLEa8Ywd/I8UHH7x4hE8DA/sUG2ldyXhl06Db7SRxYIYGl4VEMyn1YlX4K6zF1hCCV2e7TB7J4k69PlasSv6Yc4kcxTsYacRad+2K+PoZ+pDioQUTVQ)
    username: ENC(winnz9ZtTjwJbYXYAlxiNNX9tneG22w54Iao68ENhlu69kU8Tb6RdhBAxs7TkEBl)
    password: ENC(FsOUxHI5FkD/M7rTMNG9LQZdjTXdTSEXaX5VwLKt7tZk2w/h2U1kUqwjEslwMVfl)

springdoc:
  swagger-ui:
    path: /api.html

security:
  jwt:
    secret-key: ENC(dAhKEavQ1IxBR2uIPjgVpknE2KsvMwEIaMrW4d8XukOOQH9z81m3N4GwNppaL8t1jsn6QRrknOGxF4U5vy6i0Q==)
